### PR TITLE
Remove JQuery

### PR DESCRIPTION
**Pull request by kernel-io**

### CODE REVIEW

**Comment by HarenBroog** [comment]
@kernel-io what we gain by applying this change? :)

**Comment by kernel-io** [comment]
@HarenBroog we remove an un-needed dependency on jQuery? Considering the Ember team is working on decoupling Ember from jQuery I think that is a good thing.

**Comment by willviles** [comment]
@HarenBroog, check this out: [emberjs/rfcs #294](https://github.com/simonihmig/rfcs/blob/jquery-optional/text/0000-optional-jquery.md)

**Comment by HarenBroog** [comment]
@willviles @kernel-io yep, I wasn't aware of that trend, thx for contribution! I will merge it in a spare time :)

**Pull request merged**
